### PR TITLE
feat(Cache/Fixes): Added caching, Fixes a few Facebook API issues

### PR DESCRIPTION
**Pull request by silbinarywolf**
- Added caching around 'getFeed' data.
- Added two display types for Facebook (for getting posts without wall posts)
- Add non-halting error logging if Twitter feed fails
- Added sorting by created time with aggregating the provider feeds
- Updated created time to wrap in SS_Datetime for consistency
- Fixed Facebook feed to explicitly request fields so that a vanilla Facebook app setup will get the expected data
- Added a job/task for refreshing the cache pre-emptively (to avoid slow page load for certain users)

### CODE REVIEW

**Comment by silbinarywolf** [comment]
New commit:
- Moved getFeed cached logic to 'SocialFeedProvider' so each provider have it's feed accessed individually with ease
- Updated Instagram provider to throw warnings rather than just die when it fails.

**Comment by isaacrankin** [comment]
Wow, loads of nice work here 👍 

Are you able to add some documentation on how the caching works?

A few sentences in the README and comments for the methods in `/code/Providers/SocialFeedProvider.php` and `social-feed/code/SocialFeedCacheQueuedJob.php` would go a long way.

**Comment by silbinarywolf** [comment]
Yeah sure thing. I'll do that now.

**Comment by silbinarywolf** [comment]
Done.

**Pull request merged**
